# xbps-checkvers
# Autogenerated from man page /usr/share/man/man1/xbps-checkvers.1
complete -c xbps-checkvers -s C --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-checkvers -s D --description 'Specifies a full path to the void-packages repository.'
complete -c xbps-checkvers -s d --description 'Enables extra debugging shown to stderr.'
complete -c xbps-checkvers -s h --description 'Show the help message.'
complete -c xbps-checkvers -s i --description 'Check for outdated installed packages rather than in repositories.'
complete -c xbps-checkvers -s R --description 'Repository to be added to the top of the list.'
complete -c xbps-checkvers -s r --description 'Specifies a full path for the target root directory.'
complete -c xbps-checkvers -s s --description 'Shows missing binary packages comparing against the xbps-checkvers void-packa…'
complete -c xbps-checkvers -s V --description 'Show the version information.'

