#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() { "${herbstclient_command[@]:-herbstclient}" "$@" ;}

#autostart
##feh --bg-fill '/home/john/Pictures/background.jpg' &
#~/.scripts/wall_to_color.sh change
xrdb ~/.Xresources
compton -b &
feh --bg-fill "$(< "${HOME}/.cache/wal/wal")" &

source ~/.cache/wal/colors.sh

hc emit_hook reload

#xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-BackSpace quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Return spawn ${TERMINAL:-urxvt} # use your $TERMINAL with urxvt as fallback

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

#rofi
hc keybind $Mod-d spawn rofi -show drun -modi "drun,run,ssh,window" -width 30 -fg "#B0E670" -bg "#14161F" -hlfg "#14161F" -hlbg "#B0E670" -bc "#14161F" -location 0 -lines 8 -bw 0 -font "Dejavu Sans Mono 12" -opacity 90 -fuzzy -sidebar-mode -auto-select -regex -color-enabled -tokenize


# tags
tag_names=( "" "" "" "" "" "" "" "" "" )
#tag_names=( {1..9} )
tag_keys=( {1..9} ) 
#0

hc set default_frame_layout 2
hc set_layout max

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
	hc keybind "$Mod-$key" use_index "$i"
	hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c           cycle
hc keybind $Mod-i           jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#222222'
hc set frame_bg_active_color '#101010'
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 1
hc set frame_gap 4

hc attr theme.active.color '#66A3BF' #'#9fbc00'
hc attr theme.normal.color '#FFFFFF' #'#240054' #454545'
#hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#6693BF' #'#3E4A00'
hc attr theme.active.outer_color '#240054' #'#3E4A00'
hc attr theme.background_color '#141414'

hc set window_gap 7
hc set frame_padding 7
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 1
hc set focus_follows_mouse 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule instance=Dialog pseudotile=on #float for dialogs
# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
clock=~/.config/herbstluftwm/clock.sh
misc=~/.config/herbstluftwm/misc.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#if pgrep -x "lemonbar" > /dev/null; then
#	killall lemonbar
#fi
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
    "$clock" "$monitor" &
    "$misc"  "$monitor" &
done

# Pulse Audio controls
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume 0 +2% #increase sound volume
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume 0 -2% #decrease sound volume
hc keybind XF86AudioMute spawn pactl set-sink-mute 0 toggle # mute sound

# Sreen brightness controls
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 5 # increase screen brightness
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 5 # decrease screen brightness 

#Lock
hc keybind $Mod-l spawn dm-tool lock

#Notifcations
dunst &
wal -R -n -a 85

#Screen-shot
hc keybind $Mod-x spawn scrot -q 100 ~/Pictures/Screenshots/screen-`/bin/date +%Y-%m-%d--%H:%M:%S`.png -z
